import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    absolute: "Blog",
  },
  description: "Generated by Yash",
};

const About = () => {
  return <div>About</div>;
};

export default About;
