import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    absolute: "About Intercepted",
  },
  description: "Generated by Yash",
};

const InterceptedAbout = () => {
  return <div>(...)About</div>;
};

export default InterceptedAbout;
